### ISSUE TITLE
Colaboração

### ISSUE THREAD

**Issue by oggbarcelos** [themgoncalves/Cielo#1]
Olá @themgoncalves .

Temos um sistema se comunicando com a versão 1.5 da API, e precisamos migrar para a 3.0.
Encontramos seu projeto, ficou muito bom.

Não consegui analisar se seu projeto já aponta para o .NET STANDARD, sendo compatível com todas as plataformas .NET.

Se quiser ajuda conte conosco!

**Comment by themgoncalves** [comment]
Como está @gabrielrb ?

O projeto foi desenvolvido em cima do .NET Framework 4.5 devido aos requisitos de sistema, uma versão em .NET Standart está previsto para sair no fim deste mês/começo do próximo.

De qualquer forma, fique a vontade para participar! É sempre bom ter mais cabeças empenhadas na solução.

Abraços!
